[package]
name = "bzd-gw"
edition = "2024"

[dependencies]
bzd-lib = { git = "https://github.com/bez-dna/bzd-lib.git" }

axum = "0.8.4"
axum-extra = "0.10.1"

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

tokio = { version = "1.47.1", features = ["full"] }

thiserror = "2.0.16"
tracing = "0.1.41"
config = { version = "0.15.15", features = ["toml"] }
